name: Ruby

on: [push]

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.1
    - name: cache
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: v1-dependencies-{{ checksum "Gemfile.lock" }}
        restore-keys: |
          v1-dependencies-{{ checksum "Gemfile.lock" }}
          v1-dependencies-
    - name: bundle config
      run: |
        bundle config set --local path vendor/bundle
        bundle config set --local clean true
        bundle config set --local jobs 4
        bundle config set --local retry 3
    - name: Install dependencies
      run:  bundle install
    - name: Run rubocop
      run: bundle exec rubocop -P

  rspec:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        ports:
          - 33060:3306
        env:
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          BIND-ADDRESS: 0.0.0.0
    needs: rubocop
    env:
      RAILS_ENV: test
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.1
      - name: cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
          restore-keys: |
            v1-dependencies-{{ checksum "Gemfile.lock" }}
            v1-dependencies-
      - name: Replace Database Config
        run: mv config/database.yml.ci config/database.yml
      - name: bundle config
        run: |
          bundle config set --local path vendor/bundle
          bundle config set --local clean true
          bundle config set --local jobs 4
          bundle config set --local retry 3
          bundle config --local build.sassc --disable-march-tune-native
          bundle add rake
      - name: Install dependencies
        run:  bundle install
      - name: migrate
        run: |
          bundle exec rails db:prepare
      - name: Run rspec
        run: bundle exec rspec