# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8.0
        options: --health-cmd "mysqladmin ping -h localhost" --health-interval 20s --health-timeout 10s --health-retries 10
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes

    container:
      image: ruby:2.7.1-alpine
      run:
        apk add --update --no-cache \
          make \
          build-base \
          libxml2-dev \
          libxslt-dev  \
          mysql-client \
          mysql-dev \
          tzdata \
          bash \
          git \
          less \
          curl |
          gem install bundler -v ${BUNDLER_VERSION}
      env:
        BUNDLER_VERSION: 2.1.4
        DATABASE_URL: mysql2://root:@localhost:3306/inote_test

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: bundle install --jobs 4 --retry 3
    - name: Run lint
      run: bundle exec rubocop
    - name: Run tests
      run: bundle exec rspec
